import type { Config } from "tailwindcss";

export default {
  darkMode: ["class", '[data-theme="dark"]'],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      fontFamily: {
        display: ['Caveat', 'cursive'],
        hand: ['Kalam', 'cursive'],
        marker: ['"Patrick Hand"', 'cursive'],
        blueprint: ['"Architects Daughter"', 'cursive'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        paper: { DEFAULT: "hsl(var(--paper))", deep: "hsl(var(--paper-deep))" },
        ink: { DEFAULT: "hsl(var(--ink))", soft: "hsl(var(--ink-soft))" },
        pencil: "hsl(var(--pencil))",
        blueprint: { DEFAULT: "hsl(var(--blueprint))", line: "hsl(var(--blueprint-line))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        sticky: {
          yellow: "hsl(var(--sticky-yellow))",
          blue: "hsl(var(--sticky-blue))",
          pink: "hsl(var(--sticky-pink))",
          green: "hsl(var(--sticky-green))",
          indigo: "hsl(var(--sticky-indigo))",
          red: "hsl(var(--sticky-red))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        sketch: "14px 22px 16px 24px / 22px 14px 24px 16px",
      },
      boxShadow: {
        sketch: "4px 4px 0 0 hsl(var(--ink))",
        "sketch-lg": "6px 6px 0 0 hsl(var(--ink))",
        "sketch-accent": "4px 4px 0 0 hsl(var(--accent))",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(.96) rotate(-1deg)" }, "100%": { opacity: "1", transform: "scale(1) rotate(0)" } },
        wiggle: { "0%,100%": { transform: "rotate(-1deg)" }, "50%": { transform: "rotate(1deg)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in .35s ease-out",
        "scale-in": "scale-in .25s ease-out",
        wiggle: "wiggle 2.5s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
